version: '3'

services:
  ros2-rplidar:
    # rp-lidar scanner
    # The driver publishes device-dependent sensor_msgs/LaserScan data.
    build:
      context: ./rplidar
      dockerfile: Dockerfile
    tty: true
    privileged: true
    image: ros2-rplidar
    container_name: ros2-rplidar
    command: [
      "bash", "-c", "source /opt/ros/ros2_ws/src/install/setup.bash && ros2 launch /opt/ros/ros2_ws/src/rplidar_ros/launch/rplidar.launch.py"
    ]
    devices:
      - /dev/ttyUSB0
    networks:
     - ros

  ros2-rviz-rplidar:
    # run rviz client
    build:
      context: ./rviz-rplidar
      dockerfile: Dockerfile
      args:
        USER: ${USER}
        USER_ID: ${USER_ID}
    tty: true
    user: ${USER}
    image: ros2-rviz-rplidar
    container_name: ros2-rviz-rplidar
    command: [
      "rviz2", "-d", "/opt/ros/ros2_ws/src/rplidar_ros/rviz/rplidar.rviz"
    ]
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - "${XDG_RUNTIME_DIR}:/tmp/runtime-${USER}"
    environment:
      DISPLAY: ${DISPLAY}
    devices:
      - /dev/dri
      - /dev/snd
    depends_on:
      - ros2-rplidar
    networks:
      - ros

  ros2-list-topics:
    # list topics for debugging
    image: ros:dashing
    container_name: ros2-list-topics
    command: ["ros2", "topic", "list"]
    depends_on:
      - ros2-rplidar
    networks:
      - ros

networks:
  ros:
